// utils/constants.js
export const ErrorTypes = {
    USER_CONNECTION: 'USER_CONNECTION_ERROR',
    USER_DISCONNECTION: 'USER_DISCONNECTION_ERROR',
    SET_NAME: 'SET_NAME_ERROR',
    GLOBAL_PLAYERS_REQUEST: 'GLOBAL_PLAYERS_REQUEST_ERROR',
    GLOBAL_PLAYER_COUNT: 'GLOBAL_PLAYER_COUNT_ERROR',
    JOIN_LOBBY: 'JOIN_LOBBY_ERROR',
    LEAVE_LOBBY: 'LEAVE_LOBBY_ERROR',
    CREATE_LOBBY: 'CREATE_LOBBY_ERROR',
    LOBBY_PLAYERS_REQUEST: 'LOBBY_PLAYERS_REQUEST_ERROR',
    LIST_LOBBIES: 'LIST_LOBBIES_ERROR',
    CHECK_PASSWORD: 'CHECK_PASSWORD_ERROR',
    START_GAME: 'START_GAME_ERROR',
    PLAYER_READY: 'PLAYER_READY_ERROR',
    CHECK_PLAYERS_READY: 'CHECK_PLAYERS_READY_ERROR',
    END_GAME: 'END_GAME_ERROR',
    SUBMIT_SENTENCE: 'SUBMIT_SENTENCE_ERROR'
};